= La canción de mi verano

:hp-tags: Music, Poem

Poesía pura. No puedo dejar de escucharla :)

video::Zu4CoOPc3Ao[youtube]

.Los fragmentos que más me gustan (en català)
* Que el llit es converteixi en un mar esbarriat i els llençols en veles de paper d'arròs i se t'endugui un aeri oceà de peixos alats i llagostes d'ales d'aigua i que després, sentint el vertigen de ser gota d'aigua freda de pluja caiguis i et facis amiga dels calabotins i us passeu el que queda de nit xarrant i mirant les estrelles des de sota l'aigua.

* Que no siguis com tota aquesta gent que fa la veu trista per telèfon, que si plores notis que el torrent de llàgrimes et neteja.

* Que recordis que la gent és i s'és el que s'és, qui et fan ser, com s'és.

* Que estimis i et deixis estimar que sovint és la lliçó més difícil d'aprendre.

* Sigues només un infant que fa escarbots, mantingues la teva innocència lluny de l'abast dels adults i que no et venguis mai per una droga de tranquil·litat, per una punyalada amable, per una tendra esgarrapada als llavis i no siguis mai per ningú i que ningú sigui per tu, només una aixada a les pupil·les. Procura mantindre algun desig incomplert i sempre purs els orificis del cor: ulls, boca, nas i orelles i estigues contenta.

IMPORTANT: Podeis leer también la canción en castellano. Está en los comentarios del video en Youtube, en https://www.youtube.com/watch?v=Zu4CoOPc3Ao 

