= Lo que puse en Twitter el 10/11/16

:hp-tags: Twitter, news, cybersecurity, seguridad informática,

* We reverse engineer *3 chinese popular live streaming platforms* and find *keyword lists used to censor* chat messages + 
https://citizenlab.org/2016/11/harmonized-histories-year-fragmented-censorship-across-chinese-live-streaming-applications/

* The Citizen Lab (University of Toronto) is hiring a *Security Researcher to work on threats against civil society* +
https://citizenlab.org/2015/08/job-posting-security-researcher-malware-analyst/

* "Your WiFi-connected thermostat can take down the whole Internet. +
We need *new regulations*." (Bruce Schneier) via RISKS Digest

* Gran Bretaña aprueba gastar *2,3 mil millones en ciberseguridad* para, entre otros, reclutar *mil agentes de inteligencia* +  
http://www.voanews.com/a/britain-spends-billions-on-cybersecurity-russian-threat/3580433.html

* Be paranoid - *'Web Of Trust' Browser Add-On Caught* Selling Users' Data +
http://thehackernews.com/2016/11/web-of-trust-addon.html

* Cuando fuimos *netactivistas* +
https://vimeo.com/145810600

* The BlackNurse Attack "The 90's called and wanted their *ICMP flood attack back*" +  
https://www.reddit.com/r/netsec/comments/5c7g10/the_blacknurse_attack/

* @todayininfosec +
1983: *Len Eidelmen coined the term "virus"* to describe a self-replicating program during a computer safety lecture at Lehigh University.

* *Creating an IoT worm*. +
Eyal Ronen, Colin O’Flynn, Adi Shamir and Achi-Or Weingarten +
http://iotworm.eyalro.net/ +
Possible Worm applications: 
.Bricking attack
.Wireless network jamming
.Attacking the electric grid
.*Causing epileptic seizures !!!*

* What went wrong at *Tesco Bank*? + 
http://www.theregister.co.uk/2016/11/10/tesco_bank_breach_analysis/

* El legendario blog de *MalwareMustDie cierra en protesta por el mal uso de la NSA* de sus investigaciones +
http://securityaffairs.co/wordpress/53285/malware/malwaremustdie-closed.html

* The residents in two apartment buildings Finland faced more that a week of serious problem due to a *DDoS attack that targeted the building control systems* + 
http://securityaffairs.co/wordpress/53247/cyber-crime/building-control-systems-ddos.html

* *Aumentan las empresas que hacen "inteligencia"*: monitorizar la dark web por encargo de la policía + 
http://motherboard.vice.com/read/us-customs-police-paid-contractors-to-monitor-the-dark-web

* Yahoo cuesta de matar - Some Yahoo staff *knew in 2014 that it had been hacked* +
https://www.grahamcluley.com/yahoo-staff-knew-2014-hacked/ +
Yahoo is facing 23 lawsuits over that

* *New ransomware, Telecrypt, abuses Telegram* for C&C and to allow victims to send messages to attackers + 
http://www.securityweek.com/file-encrypting-ransomware-telecrypt-abuses-telegram

* *16-31 October 2016 Cyber Attacks* Timeline +
http://www.hackmageddon.com/2016/11/10/16-31-october-2016-cyber-attacks-timeline/

* *ExtraTorrent* ahogada por las acciones de la industria +
http://www.redeszone.net/2016/11/10/extratorrent-ahogada-las-acciones-la-industria/

* Blacknurse: *ataque ICMP para un DoS efectivo* y con poco ancho de banda +
http://www.hackplayers.com/2016/11/blacknurse-ataque-icmp-para-un-dos.html





